services:
  p4-clase13-api:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678" 
    volumes:
      - ./app:/app
    working_dir: /app
    env_file:
      - .env
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge